### ISSUE TITLE
Campus Advancement Staff Report

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/DM-Admin#3]
To better understand the campus partners and also provide data for current applications, we will search for the current org chart information and add that to a spreadsheet. It would also be nice to add information on who uses Workfront, eComm, CVent, etc so we know which services they are stakeholders of.

Acceptance Criteria:
- [x] Agree to the template used for tracking staff and ending summary
- [x] Add CU Boulder information
- [x] Add CU Denver information
- [x] Add CU Anschutz information
- [x] Add UCCS information
- [x] Find org chart for CU Anschutz - https://cu0.sharepoint.com/sites/Advancement/intranet/Advancement%20Files/Org%20Chart%20-%20AMC.pdf
- [x] Add web requester data to each campus sheet below the gray line 
- [x] Create a summary in Word Doc format

Resources:
- Report Spreadsheet - https://cu0.sharepoint.com/:x:/t/AdvDigitalTeam/Eah12l6M0-JHjkulUUH4oWwBV0EsGodFUB_ywECzDRBPHw?e=hXlNh3
- Report Summary Document - https://cu0.sharepoint.com/:w:/t/AdvDigitalTeam/EXvBu74LrGtOoVSGOIpbC9MBI0s1WTbNAd1RytHLKfKW0A?e=ZS0g90
- List of web requesters - https://cu0.sharepoint.com/:x:/t/AdvDigitalTeam/ERWJtMaqnCBNl410_xUnO00BjwraElHvfQ01iHzr4Z6FGg?e=ZxUdHb
- List of web requesters (de-duped) - https://cu0.sharepoint.com/:x:/t/AdvDigitalTeam/EcocCogbSb9Hr6l2p_YT0d8B7jPtxXIDQz0AXSpUDFTVzA?e=Khj2jP

Next Issue:
- Need to add this information to the Content Owners taxonomy...we could even create users on the Giving site with phone, email, name, etc.

**Comment by alexfinnarn** [comment]
Start to this issue...

![image](https://user-images.githubusercontent.com/3640707/173396797-1f5a0e3a-7723-4ffa-90f9-94784c2d9889.png)

**Comment by ktheiler** [comment]
Thanks for setting this up @alexfinnarn

**Comment by alexfinnarn** [comment]
@adha3896 Let us know what questions you have about this work.
